server:
  port: 8009
eureka:
  client:
    service-url:
      defaultZone: http:localhost:8009/eureka/
    fetch-registry: false
    register-with-eureka: false
spring:
  application:
    name: config-client