server:
  port: 8009
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8009/eureka/
spring:
  application:
    name: config-client