server:
  port: 8009
spring:
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8009/eureka/
    register-with-eureka: false
    fetch-registry: false